kind: pipeline
type: docker
name: shop

steps:
  - name: build
    image: maven:3-alpine
    volumes:
      - name: maven-repo
        path: /root/.m2
      - name: app-config
        path: /root/app-config
    commands:
      - cp -f /root/app-config/application.yml  src/main/resources/application.yml
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mkdir context
      - mv docker-entrypoint.sh context/docker-entrypoint.sh
      - mv target/shop-0.0.1-SNAPSHOT.jar context/app.jar
    when:
      branch:
        - master
      event:
        - push

  - name: push-docker
    image: plugins/docker
    settings:
      mirror: https://docker.mirrors.ustc.edu.cn
      registry: registry.cn-qingdao.aliyuncs.com
      repo: registry.cn-qingdao.aliyuncs.com/sky_55/shop-server
      tag: ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
      context: context
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker stop shop-server || true
      - docker rm shop-server || true
      - docker login -u $USERNAME -p $PASSWORD registry.cn-qingdao.aliyuncs.com
      - docker run -d -p 5555:5555 --name shop-server --restart always registry.cn-qingdao.aliyuncs.com/sky_55/shop-server:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: maven-repo
    host:
      path: /data/maven_repo
  - name: app-config
    host:
      path: /root/app-config
  - name: docker
    host:
      path: /var/run/docker.sock
