spring:
  session:
    store-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/my-shop?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: user
    password: userpass
    tomcat:
      validation-query: "select 1"
      test-on-borrow: true
      validation-interval: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 80
      jdbc-interceptors: "ResetAbandonedTimer"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

flyway:
  out-of-order: true
  baseline-on-migrate: true

demo:
  content: "test"

server:
  port: 5555

minio:
  endpoint: http://1.116.86.20:9001
  key:
    access: shop-user
    secret: ph57xCZvfPIr62h4QRofBDaaKwwLps8CVAx33UQ

sky:
  oauth2:
    default-access-token-validity-seconds: 43200 #默认12小时
    web:
      client-id: web

